# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\code\image_tools\image_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import MyView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.x0 = QtWidgets.QLineEdit(self.centralwidget)
        self.x0.setObjectName("x0")
        self.horizontalLayout.addWidget(self.x0)
        self.y0 = QtWidgets.QLineEdit(self.centralwidget)
        self.y0.setObjectName("y0")
        self.horizontalLayout.addWidget(self.y0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.x1 = QtWidgets.QLineEdit(self.centralwidget)
        self.x1.setObjectName("x1")
        self.horizontalLayout.addWidget(self.x1)
        self.y1 = QtWidgets.QLineEdit(self.centralwidget)
        self.y1.setObjectName("y1")
        self.horizontalLayout.addWidget(self.y1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.RootPath = QtWidgets.QLineEdit(self.centralwidget)
        self.RootPath.setObjectName("RootPath")
        self.horizontalLayout_3.addWidget(self.RootPath)
        self.before_button = QtWidgets.QPushButton(self.centralwidget)
        self.before_button.setObjectName("before_button")
        self.horizontalLayout_3.addWidget(self.before_button)
        self.after_button = QtWidgets.QPushButton(self.centralwidget)
        self.after_button.setObjectName("after_button")
        self.horizontalLayout_3.addWidget(self.after_button)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.SavePath = QtWidgets.QLineEdit(self.centralwidget)
        self.SavePath.setObjectName("SavePath")
        self.horizontalLayout_2.addWidget(self.SavePath)
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_button.setObjectName("Save_button")
        self.horizontalLayout_2.addWidget(self.Save_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.graphicsView =MyView.MyQGraphicsView(self.centralwidget)# QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        #self.graphicsView.viewport().installEventFilter(self)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "左上点坐标："))
        self.label_2.setText(_translate("MainWindow", "右下点坐标："))
        self.label_4.setText(_translate("MainWindow", "ImgRootPath："))
        self.before_button.setText(_translate("MainWindow", "上一张图片"))
        self.after_button.setText(_translate("MainWindow", "下一张图片"))
        self.label_3.setText(_translate("MainWindow", "SavePath："))
        self.Save_button.setText(_translate("MainWindow", "Save"))

    
